### ISSUE TITLE
JavaScript Capstone - Kanban project

### ISSUE THREAD

**Issue by Rebelzob** [Rebelzob/capstone-project-module2#22]
- For the capstone project we are 2 people working on the project, we already deleted the student C cards.
- Click [here](https://github.com/Rebelzob/capstone-project-module2/projects/1) to access to the Kanban Project

**Comment by Whoistolu** [comment]
Hi @Rebelzob and @ivangonzalez224 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [REQUIRED] Kindly ensure that all cards are assigned to team members such that each card has an avatar of a team member the task is been assigned to. NB: All cards with `group task` in the title should be assigned to someone (it does not matter to whom it is assigned).

### Your Cards
<img width="324" alt="Screenshot 2023-07-31 at 21 44 48" src="https://github.com/Rebelzob/capstone-project-module2/assets/58692590/67f86030-ca0b-457f-bb28-c3865c96e6d5">

### What it should look like (Correct card)
<img width="307" alt="Screenshot 2023-07-31 at 20 00 20" src="https://github.com/lerfast/Capstone-module2-Javacript/assets/58692590/a5c5b5ea-47a9-4efe-946f-b154535a8f71">

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

### N/A

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Rebelzob** [comment]
thanks, for the suggested changes.

**Comment by KanzaTahreem** [comment]
# Approved 🙌

Hi @Rebelzob & @ivangonzalez224 

Great work implementing the suggested changes 💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ All cards are assigned 
-  ✅ Groups tasks are assigned 
-  ✅ All cards have description

## Optional suggestions ❕
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
